---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/sonarr:/config
      - /mnt/dataYmir/:/data
      - /mnt/data/:/dataDrogo
    ports:
      - 8989:8989
    restart: unless-stopped
