---
services:
  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/jellyseer:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped
