---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/dataYmir/:/data 
    ports:
      - 7878:7878
    restart: unless-stopped
