---
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/appdata/bazarr:/config
      - /mnt/dataYmir/:/data
    ports:
      - 6767:6767
    restart: unless-stopped
